//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarastoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikkelit
    {
        public int ArtikkeliId { get; set; }
        public string Artikkelinimi { get; set; }
        public int KategoriaId { get; set; }
    
        public virtual Kategoriat Kategoriat { get; set; }
    }
}
